### ISSUE TITLE
"freeze"/"unfreeze" from master

### ISSUE THREAD

**Issue by littlepretty** [annonch/emb-vt#5]
I guess you are sending signal 10(12), which triggers freeze/unfreeze, from master to all PI devices(including master itself). Is that correct?

What do you want to accomplish in
https://github.com/annonch/emb-vt/blob/8e02b1145931a297604c775d70a4f024e7cdadf3/eval/distributed/master.sh#L122
and
https://github.com/annonch/emb-vt/blob/8e02b1145931a297604c775d70a4f024e7cdadf3/eval/distributed/master.sh#L124

**Comment by annonch** [comment]
not exactly,  these lines you have linked call 
https://github.com/annonch/emb-vt/blob/8e02b1145931a297604c775d70a4f024e7cdadf3/src/vtgpio.c#L395
which in turn changes the state of the gpioSIG,
https://github.com/annonch/emb-vt/blob/8e02b1145931a297604c775d70a4f024e7cdadf3/src/vtgpio.c#L406
which all PIs receive an asynchronous signal for either freeze or unfreeze,  because they have a hardware interrupt setup to call pause/resume when receiving a change in voltage from gpioSIG
https://github.com/annonch/emb-vt/blob/8e02b1145931a297604c775d70a4f024e7cdadf3/src/vtgpio.c#L477


On the other hand sending signal 10/12 to each other is only for evaluation of the virtual time system, to tell the PIs to collect the data from `freeze_past_time` i.e.,  https://github.com/annonch/emb-vt/blob/8e02b1145931a297604c775d70a4f024e7cdadf3/eval/distributed/local.sh#L23

Therefore since all PIs are receiving the signal in real time it is unclear what could cause this problem of the leader having slightly smaller fpt.

Let me take a look at the scripts and make them better commented so that they are easier to read :/

**Comment by littlepretty** [comment]
I see. So each of the 3 gpio (pins?) have both input and output. https://github.com/annonch/emb-vt/blob/8e02b1145931a297604c775d70a4f024e7cdadf3/src/vtgpio.c#L395
will make gpioSIG generate high/low voltage and output to all devices' gpioSIG2/3.

**Comment by annonch** [comment]
yes the wiring is just a single bus that connects all the 3 gpio pins together
